var githubName = "mquan/gitmark";
var githubToken = "4a5930a477e25feb1863693199c1ee21a6991abc";

var repo = getGitRepo(githubName, githubToken);

// Use callback style for now
repo.readRef("refs/heads/master", function(err, headHash) {
  console.log(headHash);
  repo.loadAs("commit", headHash, function(err, commit) {
    console.log(commit);
    repo.loadAs("tree", commit.tree, function(err, tree) {
      console.log(tree);
      var entry = tree["README.md"];
      console.log(entry);
      repo.loadAs("text", entry.hash, function(err, readme) {
        var updates = [
          {
            path: "README.md",
            mode: entry.mode,
            content: "this commit is generated by git.js"
          }
        ];

        updates.base = commit.tree;

        repo.createTree(updates, function(err, treeHash) {
          var commitHash = repo.saveAs("commit", {
            tree: treeHash,
            author: {
              name: "Quan Nguyen",
              email: "mquannie@gmail.com"
            },
            parent: headHash,
            message: "Change README.md from git.js"
          });

          repo.updateRef("refs/heads/master", commitHash);
        });
      })
    })
  })
});
